define: DUK_USE_NONSTD_ARRAY_SPLICE_DELCOUNT
introduced: 1.0.0
removed: 3.0.0
default: true
tags:
  - ecmascript
  - compliance
description: >
  In ES5.1 a missing deleteCount defaults to 0, but existing implementations
  default to (len - actualStart).  This is in essence a specification "bug"
  which was fixed in ES2015.  This option was removed in 3.0.0, and the
  remaining behavior matches ES2015.
