name: Test
on: [push, pull_request]
jobs:
  alltest:
    name: API and ECMA
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        slice: [ '1', '2', '3', '4', '5', '6', '7', '8' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt -qqy update
          sudo apt -qqy install build-essential make python3 python3-yaml bc git
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test
        run: |
          TZ=Europe/Helsinki make test-all-${{matrix.slice}}
  misctests:
    name: Misc tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt -qqy update
          sudo apt -qqy install build-essential make python2 python3 python3-yaml bc git valgrind
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure test
        run: |
          make configuretest
      - name: Error inject test
        run: |
          make errorinjecttest
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt -qqy update
          sudo apt -qqy install build-essential make python2 python3 python3-yaml bc git tidy
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Codepolicycheck
        run: |
          CI=1 make codepolicycheck
      - name: Tidy-site
        run: |
          make tidy-site
  sourceformat:
    name: Source format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt -qqy update
          sudo apt -qqy install make python3 python3-yaml zip unzip
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build clang-format docker image
        run: |
          make docker-image-clang-format
      - name: Reformat source, check for diff
        run: |
          make clang-format-source-check
